let FirstName = "Andy";
let LastName = "Ng";
let Age = 20;
let Address = "Granville";
let DateOfBirth = "01/01/2000";
console.log("FirstName:",FirstName);
console.log("LastName:", LastName);
console.log("Age:", Age);
console.log("Address:",Address);
console.log("DateOfBirt:", DateOfBirth);