var FirstName = "Andy";
var LastName = "Ng";
var Age = 20;
var Address = "Granville";
var DateOfBirth = "01/01/2000";
console.log(FirstName);
console.log(LastName);
console.log(Age);
console.log(Address);
console.log(DateOfBirth);