const FirstName = "Andy";
const LastName = "Ng";
const Age = 20;
const Address = "Granville";
const DateOfBirth = "01/01/2000";
console.log("FirstName:",FirstName);
console.log("LastName:", LastName);
console.log("Age:", Age);
console.log("Address:",Address);
console.log("DateOfBirt:", DateOfBirth);