var FirstName = "Andy";
var LastName = "Ng";
var Age = 20;
var Address = "Granville";
var DateOfBirth = "01/01/2000";
console.log("FirstName:",FirstName);
console.log("LastName:", LastName);
console.log("Age:", Age);
console.log("Address:",Address);
console.log("DateOfBirt:", DateOfBirth);